# Example configuration for plug-and-play neural network selection in NeuroFuzzyHybrid
# You can use this file as a template for your agents or experiments.

nn_config:
  # Select the neural network type by name (must be registered)
  nn_type: FeedforwardNeuralNetwork  # or ConvolutionalNeuralNetwork, etc.

  # Parameters for FeedforwardNeuralNetwork
  input_dim: 4
  hidden_dim: 8
  output_dim: 2
  activation: tanh  # Allowed: tanh, relu, sigmoid

# To use a different network, just change nn_type and supply required params, e.g.:
# nn_type: ConvolutionalNeuralNetwork
# input_shape: [28, 28, 1]
# num_filters: 16
# kernel_size: 3
# output_dim: 10
# activation: !!python/name:numpy.tanh

# This config can be loaded and passed to NeuroFuzzyHybrid, which will instantiate the correct network.
