name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true
        pip install flake8 pytest
    - name: Check plugin tests coverage
      run: |
        python scripts/check_plugin_tests.py
    - name: Lint plugins
      run: |
        flake8 src/env/ src/agents/ src/plugins/
    - name: Run all tests
      run: |
        pytest --maxfail=1 --disable-warnings
